#!/bin/bash

TEMPLATE=$1
TMP=/tmp
TEMPLATES_FILE=~/.local/share/kdevfiletemplates/templates/
DIR=$(basename "$TEMPLATE")
PATH_TEMPLATE=$(dirname "$TEMPLATE")


# Create KDevApp templates directory, as necessary.

if [ ! -d "$TEMPLATES_FILE" ]; then	mkdir -p "$TEMPLATES_FILE";	fi


# Build tarball and move into templates directory

if [ -d "$TEMPLATE" ]; then

    if compgen -G "$TEMPLATE/$DIR".desktop > /dev/null; then

        tar -cvjf "$TMP/$DIR.tar.bz2" -C "$PATH_TEMPLATE/$DIR" .
        mv "$TMP/$DIR.tar.bz2" "$TEMPLATES_FILE"

    else

        echo "$1 is not a KDevelop application template directory"

    fi

else

    echo "$1 is not a directory or does not exist"

fi
